spring.application.name=management
#spring.datasource.url = jdbc:mysql://localhost:3306/inventory_management
#spring.datasource.username = root
#spring.datasource.password = root123
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


app.mail.from=your-email@gmail.com

jwt.secret=${JWT_SECRET:THIS_IS_A_SECRET_KEY_FOR_JWT_UNDERSTANDING_IT_SHOULD_BE_OF_32_BYTES}
jwt.expiration=${JWT_EXPIRATION:3600000}


# SMTP Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=vishalpatil.dev2@gmail.com
#spring.mail.password=Vmh24#4995

## SMTP Properties
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#If you're using Gmail:
#
#Enable 2-Step Verification on your Google account.
#Generate an App Password.
#Use the App Password in spring.mail.password instead of your Gmail login password.